dictionaries = ["en_us"]
words = [
	"ansi",
	"arkregex",
	"arktype",
	"arraybuffer",
	"ascii",
	"bundler",
	"calt",
	"checkmark",
	"cjs",
	"codebook",
	"codepoint",
	"codesearch",
	"codestral",
	"committerdate",
	"confbox",
	"consola",
	"datastore",
	"ded",
	"deno",
	"docusaurus",
	"domhandler",
	"esc",
	"esm",
	"exa",
	"fuzzysort",
	"gamepass",
	"gamepasses",
	"htmlparser",
	"ianitor",
	"ide",
	"iex",
	"irm",
	"jndex",
	"jsr",
	"keybinds",
	"kimi",
	"kndex",
	"knip",
	"liga",
	"markdownlint",
	"matcher",
	"matchers",
	"mcp",
	"mkdir",
	"nanostores",
	"nobserve",
	"numstat",
	"objectname",
	"openai",
	"oxc",
	"oxfmt",
	"oxfmtrc",
	"oxlint",
	"oxlintrc",
	"pbcopy",
	"picocolors",
	"pnpm",
	"profilebegin",
	"profileend",
	"proj",
	"reflog",
	"roact",
	"roblox",
	"sed",
	"shfmt",
	"shitsheet",
	"smartupdate",
	"spritesheet",
	"spritesheets",
	"taplo",
	"timesheet",
	"todoread",
	"todowrite",
	"tombi",
	"toon",
	"toplevel",
	"tradeoffs",
	"tsc",
	"tsgo",
	"tsgolint",
	"typebox",
	"upng",
	"uvx",
	"vlt",
	"vscdb",
	"vscode",
	"vtsls",
	"wakatime",
	"webfetch",
	"websearch",
	"xclip",
	"zedokai",
	"zprofile",
	"zshenv",
	"世",
	"界",
]
